name: CD (Deploy)

on:
  push:
    branches:
      - main

jobs:
  train-and-promote:
    name: Run DVC Pipeline & Promote Model
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USER }}/Credit-Card-Fraud-Detection.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USER }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Configure DagsHub DVC Remote
        env:
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user $DAGSHUB_USER
          dvc remote modify origin --local password $DAGSHUB_TOKEN

      - name: Pull Data
        run: dvc pull -f -r origin

      - name: Run Pipeline (Train & Evaluate)
        run: dvc repro

      - name: Promote Model
        run: python -m src.training.promote

      - name: Push New Artifacts to DagsHub
        run: dvc push -r origin
